### PR TITLE
Add string methods visitor code to support all OData string methods

### PR DESCRIPTION
**Pull request by cdroulers**
http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#FilterSystemQueryOption

All the functions from the top of the table are supported now!

Tests were added!

### CODE REVIEW

**Comment by cdroulers** [comment]
They don't work with nested methods (e.g. toupper(substring(Name, 1, 2))) yet. Will have to add more thorough tests and refactor the code to be more recursive / awesomer.

**Comment by Pathoschild** [comment]
Sorry for the slow response! This looks fine. I added you as a contributor so you can commit changes directly. :)

**Comment by cdroulers** [comment]
Can you add me as an author on nuget.org so I can build and push the package?

**Comment by Pathoschild** [comment]
Sure. What's your NuGet username?

**Comment by cdroulers** [comment]
cdroulers

**Comment by Pathoschild** [comment]
Fair enough. You can now manage to the NuGet package too.

**Pull request merged**
