### PR TITLE
Fix lack of re-entracy that was causing two deep if blocks to not be …

### PR DESCRIPTION
**Pull request by Benjamin-Berry**
…removed.

Fix for issue. Visitor wasn't revisiting child nodes.

#9

### CODE REVIEW

**Comment by cdroulers** [comment]
Would be great if you could add a unit test that verifies the behaviour!

**Comment by Benjamin-Berry** [comment]
I think I have one but the tests don't run and I don't have time to mess with the nuget dependencies.

Running the [TestCase("$filter=Parent/Component/Two eq 61", 1)] case with $count should do it.

**Comment by cdroulers** [comment]
I added the following test in `master`, but it passes without your fix. I'm not familiar with the `$count` property.

```csharp
[Test]
public void When_counting_Then_works()
{
	var odataQuery = Helpers.Build<Child>("$count?$filter=Parent/Component/Two eq 61");
	var children = this._session.Query<Child>();
	children = FixOdataQueryAttribute.ApplyFix(children);

	var results = odataQuery.ApplyTo(children).Cast<dynamic>().ToList();
	Assert.That(results, Is.Not.Null);
}
```

I'll commit my fixes to nuget deps and this test to master, maybe you can merge in your branch and the tests should run without trouble then.

**Comment by cdroulers** [comment]
https://github.com/Pathoschild/webapi.nhibernate-odata/commit/574bf4bb6f82e09f4e810f916e6c57da4ae5d8ec

Hope this helps! I'll merge and package as soon as possible when we have a test!

**Comment by cdroulers** [comment]
https://www.nuget.org/packages/Pathoschild.WebApi.NHibernate-OData Published! Let me know if everything works!

**Pull request merged**
